{{- if .Values.enableDbMigration }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-db-migration-{{ now | date "200601021504" }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      containers:
        - name: "{{ .Release.Name }}-db-migration"
          imagePullPolicy: IfNotPresent
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: ["migrate"]
          env:
            - name: DATABASE_URL
              value: {{ .Values.env.DATABASE_URL }}
            - name: SECRET_KEY_BASE
              value: {{ .Values.env.SECRET_KEY_BASE }}
      restartPolicy: Never
{{- end }}
